import csv
import urllib.parse

categories = {
    "Grains & Rice": "8B5E3C",
    "Pulses & Dals": "C9A227",
    "Cooking Oil": "E8B923",
    "Spices & Masala": "D2691E",
    "Vegetables": "3CB043",
    "Fruits": "E4572E",
    "Dairy": "6C757D",
    "Snacks": "F4A300",
    "Beverages": "2E86AB",
    "Bakery": "C68E17",
    "Cleaning Supplies": "5DADE2",
    "Personal Care": "AF7AC5",
}

items = [
    ("Basmati Rice", "Grains & Rice", "kg", 120),
    ("Sona Masoori Rice", "Grains & Rice", "kg", 65),
    ("Idli Rice", "Grains & Rice", "kg", 55),
    ("Broken Wheat (Dalia)", "Grains & Rice", "kg", 45),
    ("Wheat Flour (Atta)", "Grains & Rice", "kg", 48),
    ("Maida (All Purpose Flour)", "Grains & Rice", "kg", 42),
    ("Rava (Semolina)", "Grains & Rice", "kg", 50),
    ("Poha (Flattened Rice)", "Grains & Rice", "kg", 60),
    ("Vermicelli", "Grains & Rice", "kg", 70),
    ("Ragi Flour", "Grains & Rice", "kg", 80),
    ("Toor Dal", "Pulses & Dals", "kg", 140),
    ("Moong Dal", "Pulses & Dals", "kg", 130),
    ("Chana Dal", "Pulses & Dals", "kg", 95),
    ("Urad Dal", "Pulses & Dals", "kg", 135),
    ("Masoor Dal", "Pulses & Dals", "kg", 100),
    ("Rajma (Kidney Beans)", "Pulses & Dals", "kg", 150),
    ("Chickpeas (Kabuli Chana)", "Pulses & Dals", "kg", 90),
    ("Green Peas (Dried)", "Pulses & Dals", "kg", 85),
    ("Black Eyed Peas", "Pulses & Dals", "kg", 95),
    ("Horse Gram", "Pulses & Dals", "kg", 80),
    ("Sunflower Oil", "Cooking Oil", "litre", 140),
    ("Groundnut Oil", "Cooking Oil", "litre", 190),
    ("Coconut Oil", "Cooking Oil", "litre", 210),
    ("Mustard Oil", "Cooking Oil", "litre", 160),
    ("Sesame Oil (Gingelly)", "Cooking Oil", "litre", 250),
    ("Olive Oil", "Cooking Oil", "litre", 550),
    ("Vanaspati (Dalda)", "Cooking Oil", "kg", 130),
    ("Ghee (Cow)", "Cooking Oil", "kg", 620),
    ("Turmeric Powder", "Spices & Masala", "kg", 180),
    ("Red Chilli Powder", "Spices & Masala", "kg", 220),
    ("Coriander Powder", "Spices & Masala", "kg", 160),
    ("Cumin Seeds (Jeera)", "Spices & Masala", "kg", 380),
    ("Mustard Seeds", "Spices & Masala", "kg", 140),
    ("Garam Masala", "Spices & Masala", "kg", 450),
    ("Sambar Powder", "Spices & Masala", "kg", 320),
    ("Rasam Powder", "Spices & Masala", "kg", 300),
    ("Black Pepper Whole", "Spices & Masala", "kg", 650),
    ("Cardamom (Elaichi)", "Spices & Masala", "kg", 2200),
    ("Cloves (Laung)", "Spices & Masala", "kg", 900),
    ("Cinnamon Stick", "Spices & Masala", "kg", 500),
    ("Salt (Iodised)", "Spices & Masala", "kg", 22),
    ("Onion", "Vegetables", "kg", 35),
    ("Potato", "Vegetables", "kg", 30),
    ("Tomato", "Vegetables", "kg", 40),
    ("Carrot", "Vegetables", "kg", 45),
    ("Beans", "Vegetables", "kg", 50),
    ("Cabbage", "Vegetables", "kg", 25),
    ("Cauliflower", "Vegetables", "kg", 35),
    ("Brinjal", "Vegetables", "kg", 40),
    ("Ladies Finger (Okra)", "Vegetables", "kg", 45),
    ("Green Chilli", "Vegetables", "kg", 60),
    ("Ginger", "Vegetables", "kg", 90),
    ("Garlic", "Vegetables", "kg", 150),
    ("Cucumber", "Vegetables", "kg", 30),
    ("Bottle Gourd", "Vegetables", "kg", 25),
    ("Pumpkin", "Vegetables", "kg", 28),
    ("Beetroot", "Vegetables", "kg", 40),
    ("Spinach (Palak)", "Vegetables", "bunch", 15),
    ("Coriander Leaves", "Vegetables", "bunch", 10),
    ("Mint Leaves", "Vegetables", "bunch", 10),
    ("Banana", "Fruits", "kg", 50),
    ("Apple", "Fruits", "kg", 180),
    ("Orange", "Fruits", "kg", 90),
    ("Mango", "Fruits", "kg", 120),
    ("Papaya", "Fruits", "kg", 40),
    ("Watermelon", "Fruits", "kg", 25),
    ("Grapes", "Fruits", "kg", 100),
    ("Pomegranate", "Fruits", "kg", 160),
    ("Guava", "Fruits", "kg", 60),
    ("Pineapple", "Fruits", "piece", 50),
    ("Milk (Full Cream)", "Dairy", "litre", 66),
    ("Curd (Yogurt)", "Dairy", "kg", 60),
    ("Paneer", "Dairy", "kg", 320),
    ("Butter", "Dairy", "kg", 480),
    ("Cheese Slices", "Dairy", "pack", 120),
    ("Buttermilk", "Dairy", "litre", 25),
    ("Cream", "Dairy", "pack", 90),
    ("Potato Chips", "Snacks", "pack", 20),
    ("Banana Chips", "Snacks", "pack", 40),
    ("Mixture", "Snacks", "kg", 220),
    ("Murukku", "Snacks", "kg", 260),
    ("Biscuits (Glucose)", "Snacks", "pack", 20),
    ("Cream Biscuits", "Snacks", "pack", 25),
    ("Namkeen", "Snacks", "pack", 45),
    ("Popcorn", "Snacks", "pack", 30),
    ("Tea Powder", "Beverages", "kg", 420),
    ("Coffee Powder", "Beverages", "kg", 550),
    ("Sugar", "Beverages", "kg", 45),
    ("Jaggery", "Beverages", "kg", 65),
    ("Soft Drink (Cola)", "Beverages", "bottle", 40),
    ("Fruit Juice", "Beverages", "litre", 110),
    ("Mineral Water", "Beverages", "bottle", 20),
    ("Bread (White)", "Bakery", "pack", 40),
    ("Bread (Brown)", "Bakery", "pack", 50),
    ("Rusk", "Bakery", "pack", 45),
    ("Cake (Plain)", "Bakery", "piece", 150),
    ("Detergent Powder", "Cleaning Supplies", "kg", 130),
    ("Dish Wash Liquid", "Cleaning Supplies", "bottle", 95),
    ("Floor Cleaner", "Cleaning Supplies", "litre", 110),
    ("Toilet Cleaner", "Cleaning Supplies", "bottle", 85),
    ("Soap (Bathing)", "Personal Care", "piece", 45),
    ("Shampoo", "Personal Care", "bottle", 180),
    ("Toothpaste", "Personal Care", "pack", 90),
    ("Hand Wash", "Personal Care", "bottle", 110),
]

print(f"Total items: {len(items)}")

rows = []
for name, cat, unit, price in items:
    color = categories[cat]
    encoded_name = urllib.parse.quote(name.replace(" ", "\n"))
    image_url = f"https://placehold.co/300x300/{color}/FFFFFF?text={encoded_name}&font=roboto"
    rows.append({
        "Name": name,
        "Category": cat,
        "Unit": unit,
        "Price": price,
        "Image_URL": image_url,
    })

out_path = "sample_data/provision_store_100_items.csv"
with open(out_path, "w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=["Name", "Category", "Unit", "Price", "Image_URL"])
    writer.writeheader()
    writer.writerows(rows)

print(f"CSV written: {out_path}, {len(rows)} rows")
