import csv

# category -> hex color (for placeholder fallback images)
categories = {
    "Pain Relief": "E63946",
    "Fever & Cold": "F4A261",
    "Antibiotics": "2A9D8F",
    "Digestive Care": "8D5A97",
    "Vitamins & Supplements": "F2C14E",
    "Diabetes Care": "5B7FBD",
    "Skin Care": "E8A0BF",
    "First Aid": "6C757D",
    "Baby Care": "70C1B3",
    "Personal Hygiene": "AF7AC5",
    "Ayurvedic": "6B8E23",
    "Medical Devices": "4A4E69",
}

# (name, category, unit, price, requires_prescription, wiki_search_term)
items = [
    ("Paracetamol 500mg", "Pain Relief", "strip", 18, False, "Paracetamol"),
    ("Ibuprofen 400mg", "Pain Relief", "strip", 25, False, "Ibuprofen"),
    ("Aspirin 75mg", "Pain Relief", "strip", 15, False, "Aspirin"),
    ("Diclofenac Gel", "Pain Relief", "tube", 85, False, "Diclofenac"),
    ("Volini Spray", "Pain Relief", "bottle", 180, False, "Analgesic"),
    ("Combiflam Tablet", "Pain Relief", "strip", 32, False, "Ibuprofen"),
    ("Naproxen 250mg", "Pain Relief", "strip", 40, True, "Naproxen"),
    ("Tramadol 50mg", "Pain Relief", "strip", 55, True, "Tramadol"),
    ("Cetirizine 10mg", "Fever & Cold", "strip", 12, False, "Cetirizine"),
    ("Paracetamol Syrup (Children)", "Fever & Cold", "bottle", 65, False, "Paracetamol"),
    ("Vicks Vaporub", "Fever & Cold", "jar", 95, False, "Menthol"),
    ("Benadryl Cough Syrup", "Fever & Cold", "bottle", 110, False, "Cough_syrup"),
    ("Crocin Advance", "Fever & Cold", "strip", 28, False, "Paracetamol"),
    ("Sinarest Tablet", "Fever & Cold", "strip", 35, False, "Common_cold"),
    ("Levocetirizine 5mg", "Fever & Cold", "strip", 20, False, "Levocetirizine"),
    ("D-Cold Total", "Fever & Cold", "strip", 30, False, "Common_cold"),
    ("Azithromycin 500mg", "Antibiotics", "strip", 95, True, "Azithromycin"),
    ("Amoxicillin 500mg", "Antibiotics", "strip", 75, True, "Amoxicillin"),
    ("Ciprofloxacin 500mg", "Antibiotics", "strip", 60, True, "Ciprofloxacin"),
    ("Doxycycline 100mg", "Antibiotics", "strip", 50, True, "Doxycycline"),
    ("Metronidazole 400mg", "Antibiotics", "strip", 40, True, "Metronidazole"),
    ("Cefixime 200mg", "Antibiotics", "strip", 110, True, "Cefixime"),
    ("Ofloxacin 200mg", "Antibiotics", "strip", 65, True, "Ofloxacin"),
    ("Antacid Gel (Digene)", "Digestive Care", "bottle", 85, False, "Antacid"),
    ("Omeprazole 20mg", "Digestive Care", "strip", 45, False, "Omeprazole"),
    ("ORS Powder", "Digestive Care", "pack", 20, False, "Oral_rehydration_therapy"),
    ("Domperidone 10mg", "Digestive Care", "strip", 30, False, "Domperidone"),
    ("Eno Fruit Salt", "Digestive Care", "pack", 15, False, "Antacid"),
    ("Lactulose Syrup", "Digestive Care", "bottle", 120, False, "Lactulose"),
    ("Ranitidine 150mg", "Digestive Care", "strip", 35, False, "Ranitidine"),
    ("Multivitamin Tablets", "Vitamins & Supplements", "bottle", 150, False, "Multivitamin"),
    ("Vitamin C 500mg", "Vitamins & Supplements", "bottle", 130, False, "Vitamin_C"),
    ("Vitamin D3 Sachet", "Vitamins & Supplements", "pack", 90, False, "Vitamin_D"),
    ("Calcium + D3 Tablets", "Vitamins & Supplements", "bottle", 160, False, "Calcium_supplement"),
    ("Zinc Tablets", "Vitamins & Supplements", "bottle", 110, False, "Zinc_supplement"),
    ("Iron Folic Acid Tablets", "Vitamins & Supplements", "strip", 45, False, "Folic_acid"),
    ("Fish Oil Omega-3 Capsules", "Vitamins & Supplements", "bottle", 320, False, "Fish_oil"),
    ("Protein Powder", "Vitamins & Supplements", "tin", 899, False, "Whey_protein"),
    ("Biotin Tablets", "Vitamins & Supplements", "bottle", 250, False, "Biotin"),
    ("Glucometer Test Strips", "Diabetes Care", "pack", 450, False, "Glucose_meter"),
    ("Insulin Syringe", "Diabetes Care", "pack", 90, True, "Insulin_syringe"),
    ("Metformin 500mg", "Diabetes Care", "strip", 25, True, "Metformin"),
    ("Glimepiride 2mg", "Diabetes Care", "strip", 40, True, "Glimepiride"),
    ("Diabetic Foot Cream", "Diabetes Care", "tube", 180, False, "Diabetic_foot"),
    ("Sugar Free Sachets", "Diabetes Care", "box", 60, False, "Sugar_substitute"),
    ("Calamine Lotion", "Skin Care", "bottle", 75, False, "Calamine"),
    ("Betadine Ointment", "Skin Care", "tube", 65, False, "Povidone-iodine"),
    ("Clotrimazole Cream", "Skin Care", "tube", 55, False, "Clotrimazole"),
    ("Moisturizing Lotion", "Skin Care", "bottle", 190, False, "Moisturizer"),
    ("Sunscreen SPF50", "Skin Care", "tube", 320, False, "Sunscreen"),
    ("Acne Gel", "Skin Care", "tube", 140, False, "Acne"),
    ("Antifungal Powder", "Skin Care", "bottle", 85, False, "Antifungal"),
    ("Cotton Roll", "First Aid", "pack", 40, False, "Cotton"),
    ("Adhesive Bandage Strips", "First Aid", "box", 35, False, "Adhesive_bandage"),
    ("Antiseptic Liquid (Dettol)", "First Aid", "bottle", 95, False, "Antiseptic"),
    ("Gauze Bandage Roll", "First Aid", "piece", 25, False, "Bandage"),
    ("Crepe Bandage", "First Aid", "piece", 45, False, "Bandage"),
    ("Hydrogen Peroxide", "First Aid", "bottle", 40, False, "Hydrogen_peroxide"),
    ("Thermometer (Digital)", "First Aid", "piece", 150, False, "Medical_thermometer"),
    ("Burn Ointment", "First Aid", "tube", 70, False, "Burn"),
    ("Baby Diapers (Pack of 20)", "Baby Care", "pack", 350, False, "Diaper"),
    ("Baby Powder", "Baby Care", "bottle", 120, False, "Talcum_powder"),
    ("Baby Lotion", "Baby Care", "bottle", 180, False, "Lotion"),
    ("Gripe Water", "Baby Care", "bottle", 85, False, "Gripe_water"),
    ("Baby Shampoo", "Baby Care", "bottle", 160, False, "Shampoo"),
    ("Baby Wipes", "Baby Care", "pack", 95, False, "Wet_wipe"),
    ("Feeding Bottle Cleanser", "Baby Care", "bottle", 130, False, "Detergent"),
    ("Hand Sanitizer 500ml", "Personal Hygiene", "bottle", 150, False, "Hand_sanitizer"),
    ("Face Masks (Pack of 50)", "Personal Hygiene", "pack", 200, False, "Surgical_mask"),
    ("Hand Wash Liquid", "Personal Hygiene", "bottle", 90, False, "Liquid_soap"),
    ("Sanitary Pads", "Personal Hygiene", "pack", 65, False, "Sanitary_napkin"),
    ("Toothbrush (Soft)", "Personal Hygiene", "piece", 40, False, "Toothbrush"),
    ("Mouthwash", "Personal Hygiene", "bottle", 130, False, "Mouthwash"),
    ("Nail Cutter Set", "Personal Hygiene", "piece", 60, False, "Nail_clipper"),
    ("Chyawanprash", "Ayurvedic", "jar", 220, False, "Chyawanprash"),
    ("Ashwagandha Capsules", "Ayurvedic", "bottle", 280, False, "Withania_somnifera"),
    ("Triphala Powder", "Ayurvedic", "pack", 90, False, "Triphala"),
    ("Neem Tablets", "Ayurvedic", "bottle", 150, False, "Azadirachta_indica"),
    ("Giloy Juice", "Ayurvedic", "bottle", 175, False, "Tinospora_cordifolia"),
    ("Amla Juice", "Ayurvedic", "bottle", 160, False, "Phyllanthus_emblica"),
    ("Herbal Hair Oil", "Ayurvedic", "bottle", 195, False, "Hair_oil"),
    ("Digital Blood Pressure Monitor", "Medical Devices", "piece", 1800, False, "Sphygmomanometer"),
    ("Pulse Oximeter", "Medical Devices", "piece", 950, False, "Pulse_oximetry"),
    ("Nebulizer Machine", "Medical Devices", "piece", 2200, False, "Nebulizer"),
    ("Weighing Scale (Digital)", "Medical Devices", "piece", 850, False, "Weighing_scale"),
    ("Hot Water Bag", "Medical Devices", "piece", 220, False, "Hot_water_bottle"),
    ("Ice Bag", "Medical Devices", "piece", 180, False, "Ice_pack"),
    ("Knee Support Brace", "Medical Devices", "piece", 350, False, "Knee_pad"),
    ("Wheelchair (Basic)", "Medical Devices", "piece", 4500, False, "Wheelchair"),
    ("Walking Stick", "Medical Devices", "piece", 300, False, "Walking_stick"),
    ("N95 Mask (Pack of 10)", "Personal Hygiene", "pack", 250, False, "Respirator"),
    ("Deworming Tablets", "Digestive Care", "strip", 20, False, "Anthelmintic"),
    ("Laxative Syrup", "Digestive Care", "bottle", 95, False, "Laxative"),
    ("Cough Lozenges", "Fever & Cold", "pack", 40, False, "Throat_lozenge"),
    ("Nasal Spray", "Fever & Cold", "bottle", 110, False, "Nasal_spray"),
    ("Steam Inhaler", "Medical Devices", "piece", 450, False, "Steam_inhalation"),
    ("Muscle Relaxant Tablet", "Pain Relief", "strip", 45, True, "Muscle_relaxant"),
    ("Anti-allergy Syrup", "Fever & Cold", "bottle", 80, False, "Antihistamine"),
    ("Eye Drops (Lubricant)", "First Aid", "bottle", 65, False, "Eye_drop"),
    ("Ear Drops", "First Aid", "bottle", 55, False, "Ear_drop"),
    ("Glucose Powder (Glucon-D)", "Digestive Care", "pack", 120, False, "Glucose"),
    ("Vitamin B Complex", "Vitamins & Supplements", "bottle", 140, False, "B_vitamins"),
    ("Probiotic Capsules", "Digestive Care", "bottle", 260, False, "Probiotic"),
]

print(f"Total pharmacy items: {len(items)}")

rows = []
for name, cat, unit, price, rx, wiki_term in items:
    rows.append({
        "Name": name,
        "Category": cat,
        "Unit": unit,
        "Price": price,
        "Image_URL": "",  # filled in by fetch_real_images.py-style pass
        "requires_prescription": rx,
        "wiki_term": wiki_term,
    })

out_path = "sample_data/pharmacy_100_items.csv"
with open(out_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["Name", "Category", "Unit", "Price", "Image_URL", "requires_prescription", "wiki_term"])
    writer.writeheader()
    writer.writerows(rows)

print(f"Written: {out_path}")
